### ISSUE TITLE
fatal error: alsa/asoundlib.h: No such file or directory

### ISSUE THREAD

**Issue by chriswalker01** [greghesp/assistant-relay#49]
Hi,

I've had this working in the past, but I'm now trying to install it on a new server and I'm getting the following when running npm install.

I've tried npm versions v8.10.0 and v7.10.1.

Any ideas?

```
root@openhab2:/opt/assistant-relay# npm install
npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> speaker@0.3.1 install /opt/assistant-relay/node_modules/speaker
> node-gyp rebuild

make: Entering directory '/opt/assistant-relay/node_modules/speaker/build'
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c:19:10: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by ogiewon** [comment]
Ever time I have installed the v1 of assistant-relay on Raspberry Pi Stretch, I have had to install “libasound2-dev” as a pre-requisite to get past the error posted above.

**Comment by chriswalker01** [comment]
I got this working with v9.0 of nodejs.

**Comment by wantt** [comment]
sudo apt-get install libasound2-dev 

solve this problem

**Comment by Loki-Afro** [comment]
`dnf yum install alsa-lib-devel` on fedora ...

**Comment by Caarhus** [comment]
Some fantastic answers here, for anyone like me who was looking to have an application hosted on Heroku that's running into this issue, look into making an Aptfile!

It should have the following line in the file:
`libasound2-dev python-dev python-numpy python-setuptools libsndfile-dev`

**Comment by Daniel-Chin** [comment]
> Ever time I have installed the v1 of assistant-relay on Raspberry Pi Stretch, I have had to install “libasound2-dev” as a pre-requisite to get past the error posted above.

I was installing `python-rtmidi`, and got the same error. Installing `libasound2-dev` also solved my problem.
